export default [
    {
        "_id":"123",
        "topic":"Space",
        "userName":"SpaceX",
        "handle":"@spacex",
        "time":"2h",
        "image":"spacex.jpeg",
        "title":"SpaceX's Mission",
        "tuit":"You want to wake up in the morning and think the future is going to be great - and that’s what being a spacefaring civilization is all about. It’s about believing in the future and thinking that the future will be better than the past. And I can’t think of anything more exciting than going out there and being among the stars",
        "liked":true,
        "disliked":true,
        "likes":234,
        "dislikes":45,
        "replies":213,
        "retuits":432
    },
    {
        "_id":"234",
        "topic":"Traffic",
        "userName":"The Boring Company",
        "handle":"@boringcompany",
        "time":"2h",
        "image":"brcompany.jpeg",
        "title":"100s of SpaceX Starships land on Mars after a 6 month journey. 1000s of Martian colonists being building Mars Base 1",
        "tuit":"The Boring Company (TBC) is an American infrastructure and tunnel construction services company founded by Elon Musk. Its ongoing and proposed projects are designed for intra-city ('loop') transit systems.",
        "liked":true,
        "disliked":true,
        "likes":125,
        "dislikes":5,
        "replies":567,
        "retuits":635
    },
    {
        "_id":2346,
        "topic":"Space",
        "userName":"SpaceX",
        "time":"5h",
        "title":"",
        "image":"tesla2.jpeg",
        "liked":true,
        "disliked":true,
        "replies":123,
        "retuits":432,
        "likes":223,
        "dislikes":656,
        "handle":"@spacex",
        "tuit":"The Tesla Cybertruck looks like it was dropped off by an alien race, but it has the capabilities to challenge all of the top-selling pickup trucks. With a sharp-edged exterior that is made of scratch- and dent-resistant stainless steel, Tesla's all-electric truck is seriously tough. Along with available all-wheel drive, the Cybertruck can tow up to 14,000 pounds and has an estimated driving range of 500-plus miles. While that applies only to the most expensive model, the cheapest one starts at $39,900. Of course, there's still a lot we don't know about the Cybertruck, including when it will officially go on sale."
    }
];
